### PR TITLE
Add new Log

### PR DESCRIPTION
**Pull request by mamantoha**
* __breaking change__ Minimum required Crystal version is `0.34.0`
* Replace `Logger` with `Log` from Crystal 0.34.0
* Add `Bot#stop` method
* Add spec for `Log`
* Update readme
* Run `crystal tool format`

### CODE REVIEW

**Comment by mamantoha** [comment]
Hi @hangyas . It would be nice if you set up Travis CI for this repository.

**Comment by hangyas** [comment]
I agree! A lot of things would be nice, e.g. the library is several versions behind the API. I'm going to pick up the work on this sometime soon and review your PR as well

**Comment by hangyas** [comment]
@mamantoha do you have any particular reason to choose this library over [tourmaline](https://github.com/protoncr/tourmaline)? I'm considering merging your PR, then deprecating this library, because every improvement I have in mind, would just make it more similar to tourmaline

**Comment by mamantoha** [comment]
Hi @hangyas . I chose it because it was the first one I found on Github. I will try tourmaline. Both libraries look similar.
If you decide to deprecate this shard please do not delete the repository from Github.
Thanks.

**Comment by mamantoha** [comment]
@hangyas also, I think it would be reasonable not to accept PRs with new features, BUT to accept PRs that fixing compatibility with new versions of Crystal. At least before release Crystal 1.0.

**Comment by hangyas** [comment]
Yes, I absolutely plan to keep the repository available and try to update it for future versions of Crystal. However, I don't really use Crystal nowadays, so it's possible that I won't notice when it breaks, PRs and issues will be welcomed

**Comment by mamantoha** [comment]
Thanks, @hangyas

**Pull request merged**
